export const myProjects = [
    {
      id:1,
      title: "react 1 project",
      category: ["react"],
      shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
      longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
      
      imgPath: "./images/1.jpg",
      link:'https://www.google.com',
      github:'https://www.github.com',
      rank:10,
      active:true
    },
    {
        id:2,
        title: "react 2 project",
        category: ["react"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/1.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:3,
        title: "react 3 project",
        category: ["react"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/1.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:4,
        title: "python 1 project",
        category: ["python"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/2.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:5,
        title: "python 2 project",
        category: ["python"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/2.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:6,
        title: "react native 1 project",
        category: ["reactnative"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/3.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:7,
        title: "react native 2 project",
        category: ["reactnative"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/3.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:8,
        title: ".Net 1 project",
        category: [".net"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/4.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:9,
        title: ".Net 2 project",
        category: [".net"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/4.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:10,
        title: "node 1 project",
        category: ["node"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/5.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:11,
        title: "node 2 project",
        category: ["node"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/5.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:12,
        title: "laravel 1  project",
        category: ["laravel"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/6.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:13,
        title: "laravel 2  project",
        category: ["laravel"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/6.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:14,
        title: "go 1  project",
        category: ["go"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/7.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
      {
        id:15,
        title: "go 2  project",
        category: ["go"],
        shortDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        longDescription:'Lorem ipsum dolor sit amet consectetur elit adipisicing . Extempore dolor in, accusantium laudantium accusamus.',
        
        imgPath: "./images/7.jpg",
        link:'https://www.google.com',
        github:'https://www.github.com',
        rank:10,
      },
  ];